name: "Project Version Bumper"
description: "Increments version number for specific project"
author: "Chris Rutkowski"
inputs:
  project:
    description: "Project name"
    required: true
  repository:
    description: "Repository to store version data"
    required: true
  token:
    description: "GitHub token"
    required: true

outputs:
  build_number:
    description: "The incremented build number"
    value: ${{ steps.set-output.outputs.build_number }}

runs:
  using: "composite"
  steps:
    - name: Clone version store and bump number
      id: set-output  # or rename to bump
      run: |
        set -e

        # git config user.name "version-bumper[bot]"
        # git config user.email "version-bumper[bot]@users.noreply.github.com"

        if ! git clone https://x-access-token:${TOKEN}@github.com/${REPOSITORY}.git versions_repository; then
          echo "❌ Failed to clone ${REPOSITORY}"
          echo "🔐 Token begins with: ${TOKEN:0:8}"
          exit 1
        fi

        cd versions_repository
        FILE="${PROJECT}.txt"
    
        if [ -f "$FILE" ]; then
          BUILD_NUMBER=$(cat $FILE)
          BUILD_NUMBER=$((BUILD_NUMBER + 1))
        else
          BUILD_NUMBER=1
        fi
        echo $BUILD_NUMBER > $FILE
        git add $FILE
        git commit -m "bump ${PROJECT} to $BUILD_NUMBER"
        git push

        echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

        # in case multiple times action is used in the workflow
        cd ..
        rm -rf versions_repository
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        PROJECT: ${{ inputs.project }}
