name: "Project Version Bumper"
description: "Increments version number for specific project"
author: "Chris Rutkowski"
inputs:
  project:
    description: "Project name"
    required: true
  repository:
    description: "Repository to store version data"
  token:
    description: "GitHub token"
    required: true

outputs:
  build_number:
    description: "The incremented build number"
    value: ${{ steps.set-output.outputs.build_number }}

runs:
  using: "composite"
  steps:
    - name: Clone version store and bump number
      id: set-output  # or rename to bump
      run: |
        git clone https://${{ inputs.token }}@github.com/${{ inputs.repository }}.git repository
        cd repository
        FILE="${{ inputs.project }}.txt"
        if [ -f "$FILE" ]; then
          BUILD_NUMBER=$(cat $FILE)
          BUILD_NUMBER=$((BUILD_NUMBER + 1))
        else
          BUILD_NUMBER=1
        fi
        echo $BUILD_NUMBER > $FILE
        git add $FILE
        git commit -m "bump ${{ inputs.project }} to $BUILD_NUMBER"
        git push
        echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
      shell: bash
